server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: functional-chat-application

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: ${CLIENT_ID}
                client-secret: ${CLIENT_SECRET}
                scope:
                  - email
                  - profile

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

logging:
  level:
    org.springframework.security: INFO
    com.karthik.functionalchatapplication: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: ConnectChat
    description: Realtime messaging platform
    version: 1.0.0